name: Test CI

on:
 push:
    branches: [ "*" ]
 pull_request:
    branches: [ "*" ]
 workflow_dispatch:

jobs:
 test_ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ansible
      uses: geerlingguy/ansible-installer@v1.2.0

    - name: Install Ansible roles
      run: |
        ansible-galaxy install -r requirements.yml

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i inventory.ini test_ci.yml