---
- name: Test CI
 hosts: webserver
 gather_facts: no
 tasks:
    - name: Ensure PHP is installed
      ansible.builtin.package:
        name: php
        state: present

    - name: Ensure Composer is installed
      ansible.builtin.package:
        name: composer
        state: present

    - name: Ensure dependencies are installed
      ansible.builtin.command:
        cmd: composer install
        chdir: ~/public_html/ynov/deploiement/test_ci/playbooks

    - name: Run PHP tests
      ansible.builtin.command:
        cmd: php ~/public_html/ynov/deploiement/test_ci/playbooks